# Generated by Django 4.2.3 on 2023-07-12 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_title', models.CharField(max_length=255)),
                ('province', models.CharField(choices=[('PH-ABR', 'Abra'), ('PH-AGN', 'Agusan del Norte[i]'), ('PH-AGS', 'Agusan del Sur'), ('PH-AKL', 'Aklan'), ('PH-ALB', 'Albay'), ('PH-ANT', 'Antique'), ('PH-APA', 'Apayao'), ('PH-AUR', 'Aurora'), ('PH-BAS', 'Basilan[iv]'), ('PH-BAN', 'Bataan'), ('PH-BTN', 'Batanes'), ('PH-BTG', 'Batangas'), ('PH-BEN', 'Benguet[vi]'), ('PH-BIL', 'Biliran'), ('PH-BOH', 'Bohol'), ('PH-BUK', 'Bukidnon'), ('PH-BUL', 'Bulacan'), ('PH-CAG', 'Cagayan'), ('PH-CAN', 'Camarines Norte'), ('PH-CAS', 'Camarines Sur[vii]'), ('PH-CAM', 'Camiguin'), ('PH-CAP', 'Capiz'), ('PH-CAT', 'Catanduanes'), ('PH-CAV', 'Cavite'), ('PH-CEB', 'Cebu[viii]'), ('PH-NCO', 'Cotabato'), ('PH-COM', 'Davao de Oro'), ('PH-DAV', 'Davao del Norte'), ('PH-DAS', 'Davao del Sur[ix]'), ('PH-DVO', 'Davao Occidental'), ('PH-DAO', 'Davao Oriental'), ('PH-DIN', 'Dinagat Islands'), ('PH-EAS', 'Eastern Samar'), ('PH-GUI', 'Guimaras'), ('PH-IFU', 'Ifugao'), ('PH-ILN', 'Ilocos Norte'), ('PH-ILS', 'Ilocos Sur'), ('PH-ILI', 'Iloilo[x]'), ('PH-ISA', 'Isabela[xi]'), ('PH-KAL', 'Kalinga'), ('PH-LUN', 'La Union'), ('PH-LAG', 'Laguna'), ('PH-LAN', 'Lanao del Norte[xii]'), ('PH-LAS', 'Lanao del Sur'), ('PH-LEY', 'Leyte[xiii]'), ('PH-MDN', 'Maguindanao del Norte[xiv]'), ('PH-MDS', 'Maguindanao del Sur'), ('PH-MAD', 'Marinduque'), ('PH-MAS', 'Masbate'), ('PH-MSC', 'Misamis Occidental'), ('PH-MSR', 'Misamis Oriental[xv]'), ('PH-MOU', 'Mountain Province'), ('PH-NEC', 'Negros Occidental[xvi]'), ('PH-NER', 'Negros Oriental'), ('PH-NSA', 'Northern Samar'), ('PH-NUE', 'Nueva Ecija'), ('PH-NUV', 'Nueva Vizcaya'), ('PH-MDC', 'Occidental Mindoro'), ('PH-MDR', 'Oriental Mindoro'), ('PH-PLW', 'Palawan[xviii]'), ('PH-PAM', 'Pampanga[xix]'), ('PH-PAN', 'Pangasinan[xx]'), ('PH-QUE', 'Quezon[xxi]'), ('PH-QUI', 'Quirino'), ('PH-RIZ', 'Rizal'), ('PH-ROM', 'Romblon'), ('PH-WSA', 'Samar'), ('PH-SAR', 'Sarangani'), ('PH-SIG', 'Siquijor'), ('PH-SOR', 'Sorsogon'), ('PH-SCO', 'South Cotabato[xxii]'), ('PH-SLE', 'Southern Leyte'), ('PH-SUK', 'Sultan Kudarat'), ('PH-SLU', 'Sulu'), ('PH-SUN', 'Surigao del Norte'), ('PH-SUR', 'Surigao del Sur'), ('PH-TAR', 'Tarlac'), ('PH-TAW', 'Tawi-Tawi'), ('PH-ZMB', 'Zambales[xxiii]'), ('PH-ZAN', 'Zamboanga del Norte'), ('PH-ZAS', 'Zamboanga del Sur[xxiv]'), ('PH-ZSI', 'Zamboanga Sibugay'), ('PH-00', 'Metro Manila')], max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('year', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], verbose_name='year')),
                ('condition', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('car_photo', models.ImageField(upload_to='photos/%m/%d/%Y/')),
                ('car_photo1', models.ImageField(blank=True, upload_to='photos/%m/%d/%Y/')),
                ('car_photo2', models.ImageField(blank=True, upload_to='photos/%m/%d/%Y/')),
                ('car_photo3', models.ImageField(blank=True, upload_to='photos/%m/%d/%Y/')),
                ('car_photo4', models.ImageField(blank=True, upload_to='photos/%m/%d/%Y/')),
                ('features', models.CharField(choices=[('Cruise Control', 'Cruise Control'), ('Audio Interface', 'Audio Interface'), ('Airbags', 'Airbags'), ('Air Conditioning', 'Air Conditioning'), ('Seat Heating', 'Seat Heating'), ('Alarm System', 'Alarm System'), ('ParkAssist', 'ParkAssist'), ('Power Steering', 'Power Steering'), ('Reversing Camera', 'Reversing Camera'), ('Direct Fuel Injection', 'Direct Fuel Injection'), ('Auto Start/Stop', 'Auto Start/Stop'), ('Wind Deflector', 'Wind Deflector'), ('Bluetooth Handset', 'Bluetooth Handset')], max_length=100)),
                ('body_style', models.CharField(max_length=100)),
                ('engine', models.CharField(max_length=100)),
                ('transmission', models.CharField(max_length=100)),
                ('interior', models.CharField(max_length=100)),
                ('miles', models.IntegerField()),
                ('doors', models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=100)),
                ('passengers', models.IntegerField()),
                ('vim_no', models.CharField(max_length=100)),
                ('milage', models.IntegerField()),
                ('fuel_type', models.CharField(max_length=100)),
                ('no_of_owners', models.CharField(max_length=100)),
                ('is_featured', models.BooleanField(max_length=100)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
